default: &default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default
  url: <%= (ENV['DATABASE_URL'] + '_test') if ENV['DATABASE_URL'].present?%>

production:
  <<: *default
